name = "seen"
main = "src/index.js"
compatibility_date = "2026-03-01"

[build]
command = "npm run build"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "seen"
database_id = "5b6bbc3e-9cf5-4ac1-a54b-cfacc22232b6"
migrations_dir = "migrations"
